name: Test HydroShare Pull Requests

on:
  push:
    # TODO: revert back to develop
    branches: [ locust-tests ]
  pull_request:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  hydroshare-pull-request-tests:

    runs-on: ubuntu-latest
    #env:
    #  COVERAGE_TOTAL: 10

    steps:
    - uses: actions/checkout@v4

    - name: Run flake8
      run: |
        python -m pip install flake8
        ./run-pylint-jenkins

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Setup HydroShare
      run: |
        printf "%s\n" c | ./local-dev-first-start-only.sh

    # TODO: revert back to run tests
    # - name: Run HydroShare Tests
    #   run: |
    #     docker exec hydroshare ./run-tests-jenkins
    
    # - name: Publish Test Results
    #   uses: EnricoMi/publish-unit-test-result-action/linux@v2
    #   if: always()
    #   with:
    #     files: |
    #       nosetests.xml
    #       pytests.xml
    
    # # archive the test results
    # - name: Archive Test Results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: test-results
    #     path: |
    #       nosetests.xml
    #       pytests.xml
    #       coverage.xml

    - name: Run Locust Load Test
      run: |
        docker exec hydroshare locust

    - name: Archive Load Results
      uses: actions/upload-artifact@v4
      with:
        name: load-results
        path: locust/reports/locust-report.html